In [115]:
import torch
a = torch.rand([3, 1000])
# two times, no genomic data is available in the other case it is
b = torch.cat([torch.zeros([2, 1000]), torch.rand([1, 1000])])

In [116]:
multimodal_features = tuple()
multimodal_features += (a,)
multimodal_features += (b,)
x = torch.stack(multimodal_features)
x

tensor([[[0.8343, 0.5954, 0.9805,  ..., 0.9251, 0.8948, 0.8371],
         [0.8937, 0.6664, 0.8984,  ..., 0.2190, 0.1414, 0.8680],
         [0.0081, 0.8910, 0.0708,  ..., 0.7521, 0.8833, 0.4126]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]]])

In [117]:
x.sum(dim=0)

tensor([[0.8343, 0.5954, 0.9805,  ..., 0.9251, 0.8948, 0.8371],
        [0.8937, 0.6664, 0.8984,  ..., 0.2190, 0.1414, 0.8680],
        [1.0081, 1.8910, 1.0708,  ..., 1.7521, 1.8833, 1.4126]])

In [118]:
x.max(dim=0)[0]

tensor([[0.8343, 0.5954, 0.9805,  ..., 0.9251, 0.8948, 0.8371],
        [0.8937, 0.6664, 0.8984,  ..., 0.2190, 0.1414, 0.8680],
        [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]])

In [119]:
x.prod(dim=0)

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0081, 0.8910, 0.0708,  ..., 0.7521, 0.8833, 0.4126]])

In [ ]:
from src.networks.embrace import EmbraceNet
from src.networks.attention import Attention
from src.networks.kronecker_fusion import kronecker_fusion
